import React from 'react';

import './App.css';
import FixedBottomNavigation from './components/BottomApBar';
import Navbar from './components/Navbar';

function App() {
  return (
    <div className="App">

      <Navbar />
      <h1> loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n </h1>
      <h1> loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n </h1>
      <h1> loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n </h1>
      <h1> loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n </h1>
      <h1> loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n </h1>
      <h1> loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n </h1>
      <h1> loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n </h1>
      <h1> loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n </h1>
      <h1> loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n </h1>
      <h1> loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n loram akwml kaml kmal kmalk malk malkn alk nakn lakn lakn alk n </h1>

      <FixedBottomNavigation />
    </div>
  );
}

export default App;
